# https://github.com/JetBrains/phpstorm-docker-images
# image: phpstorm/php-80-apache-xdebug-30
# image: phpstorm/php-74-apache-xdebug-29
# image: phpstorm/php-71-apache-xdebug-26
# image: phpstorm/php-56-apache-xdebug-25
FROM phpstorm/php-71-apache-xdebug-26